# Generated by Django 3.1.4 on 2021-05-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageM',
        ),
    ]
